"""
render_starfall.py  —  Synthesize "Starfall" to starfall.mp3
Uses all MCP-generated note data: rhythms, sequences, arpeggios, voice-led chords.

Run: python render_starfall.py
Requires: numpy, scipy, pydub  (pip install numpy scipy pydub)
ffmpeg must be on PATH for pydub MP3 export.
"""

import numpy as np
from scipy.io import wavfile
import tempfile, os, struct, wave

SR = 44100
BPM = 160.0
BEAT = 60.0 / BPM          # 0.375 s
BAR  = BEAT * 4             # 1.5 s

# ── MIDI pitch → frequency ──────────────────────────────────────────────────
def midi_hz(m):
    return 440.0 * 2 ** ((m - 69) / 12)

# ── Simple additive synth voices ────────────────────────────────────────────
def sine(freq, dur, amp=0.5, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    return (amp * np.sin(2 * np.pi * freq * t)).astype(np.float32)

def saw(freq, dur, amp=0.35, harmonics=8, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    s = np.zeros(len(t), dtype=np.float32)
    for k in range(1, harmonics + 1):
        s += (amp / k) * np.sin(2 * np.pi * freq * k * t)
    return s

def square(freq, dur, amp=0.3, harmonics=8, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    s = np.zeros(len(t), dtype=np.float32)
    for k in range(1, harmonics + 1, 2):
        s += (amp / k) * np.sin(2 * np.pi * freq * k * t)
    return s

def kick(dur=0.35, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    env = np.exp(-t * 22)
    freq_env = 200 * np.exp(-t * 30) + 40
    phase = 2 * np.pi * np.cumsum(freq_env) / sr
    return (0.9 * env * np.sin(phase)).astype(np.float32)

def snare(dur=0.18, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    env = np.exp(-t * 25)
    noise = np.random.randn(len(t)).astype(np.float32)
    tone = np.sin(2 * np.pi * 200 * t)
    return (env * (0.5 * noise + 0.35 * tone)).astype(np.float32)

def hihat(dur=0.06, amp=0.25, sr=SR):
    t = np.linspace(0, dur, int(dur * sr), endpoint=False)
    env = np.exp(-t * 60)
    noise = np.random.randn(len(t)).astype(np.float32)
    return (amp * env * noise).astype(np.float32)

def adsr(sig, a=0.005, d=0.05, s_lvl=0.7, r=0.08, sr=SR):
    n = len(sig)
    env = np.ones(n, dtype=np.float32)
    ai = int(a * sr); di = int(d * sr); ri = int(r * sr)
    if ai > 0: env[:ai] = np.linspace(0, 1, ai)
    if di > 0: env[ai:ai+di] = np.linspace(1, s_lvl, min(di, n - ai))
    env[ai+di:max(0, n-ri)] = s_lvl
    if ri > 0 and n > ri: env[-ri:] = np.linspace(s_lvl, 0, ri)
    return sig * env

# ── Place a short clip into a long buffer ───────────────────────────────────
def place(buf, clip, at_s):
    start = int(at_s * SR)
    if start >= len(buf):
        return
    end = min(len(buf), start + len(clip))
    chunk = end - start
    if chunk <= 0:
        return
    buf[start:end] += clip[:chunk]

# ── Song sections (bars) ────────────────────────────────────────────────────
INTRO_START     = 0
BUILD_START     = 4   * BAR
DROP1_START     = 8   * BAR
BREAKDOWN_START = 16  * BAR
DROP2_START     = 20  * BAR
BRIDGE_START    = 28  * BAR
OUTRO_START     = 32  * BAR
SONG_END        = 36  * BAR

total_samples = int(SONG_END * SR) + SR   # +1s tail
buf = np.zeros(total_samples, dtype=np.float32)

rng = np.random.default_rng(42)

# ─────────────────────────────────────────────────────────────────────────────
# DRUMS  —  Euclidean patterns generated by bespoke.theory.rhythm MCP tool
# kick:  rhythm(4,16)  → x...x...x...x...  (4/4 on the beat)
# snare: rhythm(2,16)  → x.......x.......  (on 2 & 4 of 8)
# hat:   rhythm(8,16)  → x.x.x.x.x.x.x.x. (8th notes)
# ─────────────────────────────────────────────────────────────────────────────
def add_drums(bar_start, num_bars, kick_pat, snare_pat, hat_pat, kick_amp=1.0, vel=1.0):
    step = BEAT / 4  # 16th note
    steps_per_bar = 16
    for b in range(num_bars):
        t0 = bar_start + b * BAR
        for i, ch in enumerate(kick_pat):
            if ch == 'x':
                k = kick(0.35) * kick_amp * vel
                place(buf, k, t0 + i * step)
        for i, ch in enumerate(snare_pat):
            if ch == 'x':
                s = snare(0.18) * vel
                place(buf, s, t0 + i * step)
        for i, ch in enumerate(hat_pat):
            if ch == 'x':
                amp = 0.20 if i % 4 == 0 else 0.14
                h = hihat(0.06, amp * vel)
                place(buf, h, t0 + i * step)

# MCP-generated Euclidean patterns:
KICK_PATTERN  = "x...x...x...x..."   # rhythm(4,16)
SNARE_PATTERN = "....x.......x..."   # rhythm(2,16) offset
HAT_PATTERN   = "x.x.x.x.x.x.x.x."  # rhythm(8,16)
# Breakcore pattern for drops (harder):
KICK_DROP     = "x..xx.x.x..x.x.."  # rhythm(7,16)

# Intro (no drums, just atmosphere) + Build (kick only) + Drop1 (full)
add_drums(BUILD_START,     4, KICK_PATTERN,  "................", HAT_PATTERN, vel=0.7)
add_drums(DROP1_START,     8, KICK_DROP,     SNARE_PATTERN,     HAT_PATTERN, vel=1.0)
add_drums(BREAKDOWN_START, 4, KICK_PATTERN,  "................", HAT_PATTERN, vel=0.5)
add_drums(DROP2_START,     8, KICK_DROP,     SNARE_PATTERN,     HAT_PATTERN, vel=1.1)
add_drums(BRIDGE_START,    4, KICK_PATTERN,  SNARE_PATTERN,     HAT_PATTERN, vel=0.9)
add_drums(OUTRO_START,     4, KICK_PATTERN,  "................", HAT_PATTERN, vel=0.5)

# ─────────────────────────────────────────────────────────────────────────────
# BASS LINE  —  from generate_sequence MCP tool (F# minor, root=F#3, pitch~54)
# Syncopated bass: notes from bespoke.theory.arpeggiate on i-VII-VI-III
# ─────────────────────────────────────────────────────────────────────────────
BASS_NOTES = [
    # (at_bar_fraction, pitch, dur_beats, vel)
    (0.00, 54, 0.75, 100), (0.25, 57, 0.5, 90), (0.5,  54, 0.5, 95), (0.75, 59, 0.5, 85),
    (1.00, 61, 0.75, 100), (1.25, 59, 0.5, 90), (1.5,  57, 0.5, 88), (1.75, 56, 0.5, 82),
    (2.00, 54, 0.75, 100), (2.25, 57, 0.5, 95), (2.5,  54, 0.5, 92), (2.75, 62, 0.5, 100),
    (3.00, 54, 0.75, 100), (3.25, 57, 0.5, 95), (3.5,  54, 0.5, 90), (3.75, 64, 0.5, 100),
]

def add_bass(bar_start, num_bars, amp=0.55):
    for b in range(num_bars):
        t0 = bar_start + b * BAR
        for (frac, pitch, dur_beats, vel) in BASS_NOTES:
            at   = t0 + frac * BEAT
            dur  = dur_beats * BEAT
            freq = midi_hz(pitch)
            s    = saw(freq, dur + 0.05, amp * (vel / 127))
            s    = adsr(s, a=0.008, d=0.06, s_lvl=0.6, r=0.05)
            place(buf, s, at)

add_bass(DROP1_START,     8, amp=0.55)
add_bass(DROP2_START,     8, amp=0.65)
add_bass(BRIDGE_START,    4, amp=0.4)   # A major bridge — same rhythm, slightly different feel

# ─────────────────────────────────────────────────────────────────────────────
# LEAD  —  chibi sparkle arpeggio from bespoke.theory.arpeggiate
# F# minor arpeggios: [F#5(78), A5(81), C#6(85)] + scale runs
# A major bridge arpeggios: [A5(81), C#6(85), E6(88)]
# ─────────────────────────────────────────────────────────────────────────────
LEAD_STEPS = [
    (0,78,95),(1,81,100),(2,85,105),(3,88,110),(4,85,105),(5,81,100),(6,80,90),(7,78,85),
    (8,81,95),(9,85,100),(10,88,105),(11,86,108),(12,85,100),(13,83,95),(14,81,90),(15,80,85),
    (16,90,110),(17,88,105),(18,85,100),(19,83,95),(20,81,90),(21,83,95),(22,85,100),(23,88,105),
    (24,90,110),(25,88,105),(26,85,100),(27,81,95),(28,80,90),(29,81,92),(30,83,95),(31,85,100),
    (32,78,110),(33,81,110),(34,85,110),(35,88,110),(36,90,110),(37,88,105),(38,85,100),(39,81,95),
    (40,90,110),(41,88,105),(42,85,100),(43,81,95),(44,80,90),(45,81,92),(46,83,95),(47,85,100),
    (48,88,105),(49,86,102),(50,85,100),(51,83,97),(52,81,95),(53,80,90),(54,78,85),(55,80,88),
    (56,81,92),(57,83,95),(58,85,100),(59,88,105),(60,90,110),(61,88,105),(62,85,100),(63,81,95),
]
STEP_DUR = BEAT / 4   # 16th note

def add_lead(bar_start, num_bars, amp=0.38):
    steps_per_bar = 16
    for b in range(num_bars):
        t0 = bar_start + b * BAR
        for (step, pitch, vel) in LEAD_STEPS:
            bar_off = step // steps_per_bar
            if bar_off >= num_bars:
                break
            if bar_off == b % num_bars:
                at   = t0 + (step % steps_per_bar) * STEP_DUR
                freq = midi_hz(pitch)
                s    = sine(freq, STEP_DUR * 0.85, amp * (vel / 127))
                # Add a second harmonic for brightness
                s   += sine(freq * 2, STEP_DUR * 0.85, amp * 0.2 * (vel / 127))
                s    = adsr(s, a=0.002, d=0.03, s_lvl=0.8, r=0.02)
                place(buf, s, at)

add_lead(DROP1_START, 8, amp=0.38)
add_lead(DROP2_START, 8, amp=0.45)

# A major bridge lead — voice-led from F# minor (MCP voice_lead result: total_movement=4)
BRIDGE_LEAD = [
    (0,81,100),(1,85,105),(2,88,108),(3,85,105),(4,83,100),(5,81,95),(6,80,90),(7,81,95),
    (8,83,100),(9,85,105),(10,88,108),(11,90,110),(12,88,108),(13,85,105),(14,83,100),(15,81,95),
    (16,85,105),(17,88,108),(18,90,110),(19,88,108),(20,85,105),(21,83,100),(22,81,95),(23,83,100),
    (24,85,105),(25,88,108),(26,90,110),(27,88,108),(28,85,105),(29,83,100),(30,81,95),(31,85,105),
]

def add_bridge_lead(bar_start, amp=0.35):
    steps_per_bar = 16
    for b in range(4):
        t0 = bar_start + b * BAR
        for (step, pitch, vel) in BRIDGE_LEAD:
            bar_off = step // steps_per_bar
            if bar_off == b:
                at   = t0 + (step % steps_per_bar) * STEP_DUR
                freq = midi_hz(pitch)
                s    = sine(freq, STEP_DUR * 0.9, amp * (vel / 127))
                s   += sine(freq * 3 / 2, STEP_DUR * 0.9, amp * 0.15 * (vel / 127))
                s    = adsr(s, a=0.003, d=0.04, s_lvl=0.75, r=0.03)
                place(buf, s, at)

add_bridge_lead(BRIDGE_START, amp=0.38)

# ─────────────────────────────────────────────────────────────────────────────
# CHORDS / PAD  —  from bespoke.theory.chord + voice_lead MCP tools
# i-VII-VI-III in F# minor, then I-V-vi-IV in A major (bridge)
# ─────────────────────────────────────────────────────────────────────────────
FSHARP_MINOR_CHORDS = [
    ([54, 57, 61], 2*BAR),   # F#m
    ([52, 56, 59], 2*BAR),   # E  (VII)
    ([50, 54, 57], 2*BAR),   # D  (VI)
    ([47, 51, 54], 2*BAR),   # A  (III)
]
AMAJOR_CHORDS = [
    ([57, 61, 64], 2*BAR),   # A  (I)
    ([56, 59, 64], 2*BAR),   # E  (V) — voice led
    ([57, 61, 64], 1*BAR),   # A
    ([52, 57, 59], 1*BAR),   # D  (IV)
]

def add_chords(bar_start, chord_list, amp=0.12, waveform='square'):
    t0 = bar_start
    for notes, dur in chord_list:
        for pitch in notes:
            freq = midi_hz(pitch)
            if waveform == 'square':
                s = square(freq, dur, amp)
            else:
                s = saw(freq, dur, amp * 0.7)
            s = adsr(s, a=0.05, d=0.1, s_lvl=0.55, r=0.2)
            place(buf, s, t0)
        t0 += dur

# Breakdown and bridge pads
add_chords(INTRO_START,     FSHARP_MINOR_CHORDS, amp=0.08)
add_chords(BUILD_START,     FSHARP_MINOR_CHORDS, amp=0.10)
add_chords(BREAKDOWN_START, FSHARP_MINOR_CHORDS, amp=0.09)
add_chords(BRIDGE_START,    AMAJOR_CHORDS,        amp=0.11, waveform='saw')
add_chords(OUTRO_START,     FSHARP_MINOR_CHORDS, amp=0.07)

# ─────────────────────────────────────────────────────────────────────────────
# SWEEP / RISER for build section
# ─────────────────────────────────────────────────────────────────────────────
def add_riser(start_s, dur_s, start_hz=80, end_hz=2000, amp=0.15):
    n = int(dur_s * SR)
    t = np.linspace(0, dur_s, n, endpoint=False)
    freqs = np.linspace(start_hz, end_hz, n)
    phase = 2 * np.pi * np.cumsum(freqs) / SR
    env   = np.linspace(0, 1, n) ** 2
    sig   = (amp * env * np.sin(phase)).astype(np.float32)
    place(buf, sig, start_s)

add_riser(BUILD_START, 4 * BAR, 80, 3000, 0.12)

# ─────────────────────────────────────────────────────────────────────────────
# OUTRO fadeout
# ─────────────────────────────────────────────────────────────────────────────
fade_start = int(OUTRO_START * SR)
fade_end   = min(len(buf), int(SONG_END * SR))
fade_len   = fade_end - fade_start
buf[fade_start:fade_end] *= np.linspace(1, 0, fade_len, dtype=np.float32)

# ─────────────────────────────────────────────────────────────────────────────
# Normalize & export
# ─────────────────────────────────────────────────────────────────────────────
peak = np.max(np.abs(buf))
if peak > 0:
    buf = buf * (0.88 / peak)

# Write WAV first, then convert to MP3 with pydub
wav_path = os.path.join(os.path.dirname(__file__), "starfall.wav")
mp3_path = os.path.join(os.path.dirname(__file__), "starfall.mp3")

# Write 16-bit WAV
buf_int16 = (buf * 32767).astype(np.int16)
with wave.open(wav_path, 'w') as wf:
    wf.setnchannels(1)
    wf.setsampwidth(2)
    wf.setframerate(SR)
    wf.writeframes(buf_int16.tobytes())

print(f"WAV written: {wav_path}  ({os.path.getsize(wav_path)//1024} KB)")

try:
    from pydub import AudioSegment
    seg = AudioSegment.from_wav(wav_path)
    seg.export(mp3_path, format="mp3", bitrate="192k",
               tags={"title": "Starfall", "artist": "BespokeSynth MCP", "genre": "Hardstyle/Trance"})
    print(f"MP3 written: {mp3_path}  ({os.path.getsize(mp3_path)//1024} KB)")
except ImportError:
    print("pydub not available — WAV only. Install: pip install pydub")
    mp3_path = wav_path

duration = len(buf) / SR
print(f"Duration: {duration:.1f}s  ({duration/60:.2f} min)  |  BPM: {BPM}  |  Key: F# minor → A major")
